# Generated by Django 4.1.1 on 2022-10-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='static/news_image/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('World News', 'World News'), ('Uzbekistan News', 'Uzbekistan News'), ('Latest News', 'Latest News')], default='Latest News', max_length=50)),
            ],
            options={
                'verbose_name': 'new',
                'verbose_name_plural': 'news',
            },
        ),
    ]
