# Generated by Django 4.1.1 on 2022-10-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='image',
            field=models.ImageField(upload_to='media/news_image/'),
        ),
    ]
